//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCubeMobile {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartCubeUWPV2023.Main.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Brand Matrix:.
        /// </summary>
        public static string AnalyzeBrandMatrix {
            get {
                return ResourceManager.GetString("AnalyzeBrandMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Conditions Dates:.
        /// </summary>
        public static string AnalyzeConditionsDates {
            get {
                return ResourceManager.GetString("AnalyzeConditionsDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Conditions_Plans:.
        /// </summary>
        public static string AnalyzeConditionsPlans {
            get {
                return ResourceManager.GetString("AnalyzeConditionsPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with: analyze costs.
        /// </summary>
        public static string AnalyzeCosts {
            get {
                return ResourceManager.GetString("AnalyzeCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Conditions_Limits: FieldName.
        /// </summary>
        public static string AnalyzeFieldName {
            get {
                return ResourceManager.GetString("AnalyzeFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Conditions_Limits: Fixed Area NOT SET.
        /// </summary>
        public static string AnalyzeFixedArea {
            get {
                return ResourceManager.GetString("AnalyzeFixedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Conditions_Limits: LimitCode.
        /// </summary>
        public static string AnalyzeLimitCode {
            get {
                return ResourceManager.GetString("AnalyzeLimitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Conditions_Limits: LimitType.
        /// </summary>
        public static string AnalyzeLimitType {
            get {
                return ResourceManager.GetString("AnalyzeLimitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Post_Limits: Field Name.
        /// </summary>
        public static string AnalyzePostFieldName {
            get {
                return ResourceManager.GetString("AnalyzePostFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Pre_Conditions:.
        /// </summary>
        public static string AnalyzePreConditions {
            get {
                return ResourceManager.GetString("AnalyzePreConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Pre_Conditions: Field Name.
        /// </summary>
        public static string AnalyzePreFieldName {
            get {
                return ResourceManager.GetString("AnalyzePreFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Tariff Engine:.
        /// </summary>
        public static string AnalyzeTariffEngine {
            get {
                return ResourceManager.GetString("AnalyzeTariffEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Tariff Matrix:.
        /// </summary>
        public static string AnalyzeTariffMatrix {
            get {
                return ResourceManager.GetString("AnalyzeTariffMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Conditions_Limits: Tier.
        /// </summary>
        public static string AnalyzeTier {
            get {
                return ResourceManager.GetString("AnalyzeTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Conditions_Limits: Tier Count.
        /// </summary>
        public static string AnalyzeTierCount {
            get {
                return ResourceManager.GetString("AnalyzeTierCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Conditions_Limits: TIER3.
        /// </summary>
        public static string AnalyzeTierThree {
            get {
                return ResourceManager.GetString("AnalyzeTierThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Vat Rates: not found.
        /// </summary>
        public static string AnalyzeVatRates {
            get {
                return ResourceManager.GetString("AnalyzeVatRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ********.
        /// </summary>
        public static string Asterisks {
            get {
                return ResourceManager.GetString("Asterisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with: lookup brand item.
        /// </summary>
        public static string BrandItem {
            get {
                return ResourceManager.GetString("BrandItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with: cancel meter.
        /// </summary>
        public static string CancelMeter {
            get {
                return ResourceManager.GetString("CancelMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot decode JSON.
        /// </summary>
        public static string CannotDecodeJson {
            get {
                return ResourceManager.GetString("CannotDecodeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Web Service Key.
        /// </summary>
        public static string CannotFindWebServiceKey {
            get {
                return ResourceManager.GetString("CannotFindWebServiceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load from Mothership.
        /// </summary>
        public static string CannotLoadFromMothership {
            get {
                return ResourceManager.GetString("CannotLoadFromMothership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation:.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with: consumer energy.
        /// </summary>
        public static string ConsumerEnergy {
            get {
                return ResourceManager.GetString("ConsumerEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Uri handler failed.
        /// </summary>
        public static string CreateHandlerFailure {
            get {
                return ResourceManager.GetString("CreateHandlerFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with: display meter.
        /// </summary>
        public static string DisplayMeter {
            get {
                return ResourceManager.GetString("DisplayMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2 Form Build Id:.
        /// </summary>
        public static string EdFSwitchStep2 {
            get {
                return ResourceManager.GetString("EdFSwitchStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3 Form Build Id:.
        /// </summary>
        public static string EdFSwitchStep3 {
            get {
                return ResourceManager.GetString("EdFSwitchStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4 Form Build Id:.
        /// </summary>
        public static string EdFSwitchStep4 {
            get {
                return ResourceManager.GetString("EdFSwitchStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 5 Form Build Id:.
        /// </summary>
        public static string EdFSwitchStep5 {
            get {
                return ResourceManager.GetString("EdFSwitchStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 5: Bank account details incorrect.
        /// </summary>
        public static string EdFSwitchStep5Bank {
            get {
                return ResourceManager.GetString("EdFSwitchStep5Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string EncryptionError {
            get {
                return ResourceManager.GetString("EncryptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure your device is connected to the Internet before signing in.
        /// </summary>
        public static string EnsureConnectedToInternet {
            get {
                return ResourceManager.GetString("EnsureConnectedToInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Account Name, Sort Code and Account Number.
        /// </summary>
        public static string EnterBankDetails {
            get {
                return ResourceManager.GetString("EnterBankDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Customer No, your Memorable data and your Passcode.
        /// </summary>
        public static string EnterLoginDetails {
            get {
                return ResourceManager.GetString("EnterLoginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Username and Password before Sign-in.
        /// </summary>
        public static string EnterUsernameAndPassword {
            get {
                return ResourceManager.GetString("EnterUsernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load:.
        /// </summary>
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothingeverworks.
        /// </summary>
        public static string FuckingChimps {
            get {
                return ResourceManager.GetString("FuckingChimps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get confirmation:.
        /// </summary>
        public static string GetConfirmation {
            get {
                return ResourceManager.GetString("GetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Greetings {
            get {
                return ResourceManager.GetString("Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \u2714.
        /// </summary>
        public static string HeavyTick {
            get {
                return ResourceManager.GetString("HeavyTick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out....
        /// </summary>
        public static string LoggingOut {
            get {
                return ResourceManager.GetString("LoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login details are incomplete.
        /// </summary>
        public static string Logindetailsincomplete {
            get {
                return ResourceManager.GetString("Logindetailsincomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOn attempted ....
        /// </summary>
        public static string LogOnAttempted {
            get {
                return ResourceManager.GetString("LogOnAttempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n.
        /// </summary>
        public static string NewLine {
            get {
                return ResourceManager.GetString("NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment:.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with: lookup payment plan.
        /// </summary>
        public static string PaymentPlan {
            get {
                return ResourceManager.GetString("PaymentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Details:.
        /// </summary>
        public static string PersonalDetails {
            get {
                return ResourceManager.GetString("PersonalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Sign-in to continue.
        /// </summary>
        public static string PleaseSignin {
            get {
                return ResourceManager.GetString("PleaseSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem: .
        /// </summary>
        public static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed:.
        /// </summary>
        public static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Id:.
        /// </summary>
        public static string QuoteId {
            get {
                return ResourceManager.GetString("QuoteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Proceed Online:.
        /// </summary>
        public static string QuoteProceedOnline {
            get {
                return ResourceManager.GetString("QuoteProceedOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Signup Code:.
        /// </summary>
        public static string ReferralSignupCode {
            get {
                return ResourceManager.GetString("ReferralSignupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup Code:.
        /// </summary>
        public static string SignupCode {
            get {
                return ResourceManager.GetString("SignupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignupLink is empty.
        /// </summary>
        public static string SignupLinkEmpty {
            get {
                return ResourceManager.GetString("SignupLinkEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address : .
        /// </summary>
        public static string SwitchAddress {
            get {
                return ResourceManager.GetString("SwitchAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Code:.
        /// </summary>
        public static string SwitchAddressCode {
            get {
                return ResourceManager.GetString("SwitchAddressCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Account Name, Sort Code and Account Number.
        /// </summary>
        public static string SwitchBankDetails {
            get {
                return ResourceManager.GetString("SwitchBankDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/Town:.
        /// </summary>
        public static string SwitchCityTown {
            get {
                return ResourceManager.GetString("SwitchCityTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation :.
        /// </summary>
        public static string SwitchConfirmation {
            get {
                return ResourceManager.GetString("SwitchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch details are incomplete.
        /// </summary>
        public static string Switchdetailsincomplete {
            get {
                return ResourceManager.GetString("Switchdetailsincomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Name:.
        /// </summary>
        public static string SwitchHouseName {
            get {
                return ResourceManager.GetString("SwitchHouseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House No:.
        /// </summary>
        public static string SwitchHouseNo {
            get {
                return ResourceManager.GetString("SwitchHouseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching now:.
        /// </summary>
        public static string SwitchingNow {
            get {
                return ResourceManager.GetString("SwitchingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Now:.
        /// </summary>
        public static string SwitchNow {
            get {
                return ResourceManager.GetString("SwitchNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with: Switchover.
        /// </summary>
        public static string Switchover {
            get {
                return ResourceManager.GetString("Switchover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        public static string SwitchStreet {
            get {
                return ResourceManager.GetString("SwitchStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with: lookup tariff item.
        /// </summary>
        public static string TariffItem {
            get {
                return ResourceManager.GetString("TariffItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate - you are not logged-in.
        /// </summary>
        public static string UnableToAuthenticate {
            get {
                return ResourceManager.GetString("UnableToAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with: update CE.
        /// </summary>
        public static string UpdateConsumerEnergy {
            get {
                return ResourceManager.GetString("UpdateConsumerEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId:.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability:.
        /// </summary>
        public static string Vulnerability {
            get {
                return ResourceManager.GetString("Vulnerability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service Key:.
        /// </summary>
        public static string WebServiceKey {
            get {
                return ResourceManager.GetString("WebServiceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be logged-in before you can run SmartSwitch.
        /// </summary>
        public static string YouNeedToBeLoggedIn {
            get {
                return ResourceManager.GetString("YouNeedToBeLoggedIn", resourceCulture);
            }
        }
    }
}
